version: '3.8'

services:
  app:
    image: exoplanetfinder:latest
    build: .
    restart: unless-stopped
    ports:
      - "8501:8501" # Interfața Streamlit
      - "8000:8000" # API-ul FastAPI
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite accesul la MySQL-ul din PC-ul tău
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      